server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3301/admin-app?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Passer@01
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin
    
  jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true